frr defaults traditional
hostname d
log stdout informational
service integrated-vtysh-config
!
router ospf
 ospf router-id 4.4.4.4
 network 10.0.4.0/24 area 0
 network 10.0.34.0/24 area 0
 network 10.0.20.0/24 area 0
!
line vty
!
